# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(db_index=True, max_length=256)),
                ('url', models.URLField(blank=True, db_index=True, null=True)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date_string', models.CharField(blank=True, max_length=256, null=True)),
                ('advertiser_name', models.CharField(max_length=256)),
                ('advertiser_phone', models.CharField(blank=True, max_length=256, null=True)),
                ('city', models.CharField(blank=True, max_length=256, null=True)),
                ('district', models.CharField(blank=True, max_length=256, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=256, null=True)),
                ('street', models.CharField(blank=True, max_length=256, null=True)),
                ('basic_features', models.TextField(blank=True, null=True)),
                ('building_features', models.TextField(blank=True, null=True)),
                ('equipment', models.TextField(blank=True, null=True)),
                ('price_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('size', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('deposit_months', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HouseImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=512, null=True)),
                ('url_small', models.URLField(blank=True, max_length=512, null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.House')),
            ],
        ),
    ]
