# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-20 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='advertiser_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
