# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_auto_20170320_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
